version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: finance_postgres_db
    environment:
      POSTGRES_USER: ${DB_USER:-fastapiuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-fastapipassword}
      POSTGRES_DB: ${DB_NAME:-finance_db}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: